// Generated by jextract

package org.drpc.logsoracle;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor rcl_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle rcl_new$MH = RuntimeHelper.downcallHandle(
        "rcl_new",
        constants$0.rcl_new$FUNC
    );
    static final FunctionDescriptor rcl_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_free$MH = RuntimeHelper.downcallHandle(
        "rcl_free",
        constants$0.rcl_free$FUNC
    );
    static final FunctionDescriptor rcl_query$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_query$MH = RuntimeHelper.downcallHandle(
        "rcl_query",
        constants$0.rcl_query$FUNC
    );
    static final FunctionDescriptor rcl_insert$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_insert$MH = RuntimeHelper.downcallHandle(
        "rcl_insert",
        constants$0.rcl_insert$FUNC
    );
    static final FunctionDescriptor rcl_logs_count$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_logs_count$MH = RuntimeHelper.downcallHandle(
        "rcl_logs_count",
        constants$0.rcl_logs_count$FUNC
    );
    static final FunctionDescriptor rcl_blocks_count$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_blocks_count$MH = RuntimeHelper.downcallHandle(
        "rcl_blocks_count",
        constants$0.rcl_blocks_count$FUNC
    );
}


