// Generated by jextract

package org.drpc.logsoracle;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final FunctionDescriptor rcl_insert$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_insert$MH = RuntimeHelper.downcallHandle(
        "rcl_insert",
        constants$1.rcl_insert$FUNC
    );
    static final FunctionDescriptor rcl_logs_count$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_logs_count$MH = RuntimeHelper.downcallHandle(
        "rcl_logs_count",
        constants$1.rcl_logs_count$FUNC
    );
    static final FunctionDescriptor rcl_blocks_count$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_blocks_count$MH = RuntimeHelper.downcallHandle(
        "rcl_blocks_count",
        constants$1.rcl_blocks_count$FUNC
    );
}


