// Generated by jextract

package org.drpc.logsoracle;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor rcl_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_open$MH = RuntimeHelper.downcallHandle(
        "rcl_open",
        constants$0.rcl_open$FUNC
    );
    static final FunctionDescriptor rcl_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_free$MH = RuntimeHelper.downcallHandle(
        "rcl_free",
        constants$0.rcl_free$FUNC
    );
    static final FunctionDescriptor rcl_update_height$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle rcl_update_height$MH = RuntimeHelper.downcallHandle(
        "rcl_update_height",
        constants$0.rcl_update_height$FUNC
    );
    static final FunctionDescriptor rcl_set_upstream$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_set_upstream$MH = RuntimeHelper.downcallHandle(
        "rcl_set_upstream",
        constants$0.rcl_set_upstream$FUNC
    );
    static final FunctionDescriptor rcl_query$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_query$MH = RuntimeHelper.downcallHandle(
        "rcl_query",
        constants$0.rcl_query$FUNC
    );
    static final FunctionDescriptor rcl_insert$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle rcl_insert$MH = RuntimeHelper.downcallHandle(
        "rcl_insert",
        constants$0.rcl_insert$FUNC
    );
}


