// Generated by jextract

package org.drpc.logsoracle;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class liboracle_h  {

    public static final OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static final OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static final OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static final OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static final OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static final OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    /**
     * {@snippet :
     * enum .HASH_LENGTH = 32;
     * }
     */
    public static int HASH_LENGTH() {
        return (int)32L;
    }
    /**
     * {@snippet :
     * enum .ADDRESS_LENGTH = 20;
     * }
     */
    public static int ADDRESS_LENGTH() {
        return (int)20L;
    }
    /**
     * {@snippet :
     * enum .TOPICS_LENGTH = 4;
     * }
     */
    public static int TOPICS_LENGTH() {
        return (int)4L;
    }
    /**
     * {@snippet :
     * enum .RCL_SUCCESS = 0;
     * }
     */
    public static int RCL_SUCCESS() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * enum .RCL_ERROR_MEMORY_ALLOCATION = 1;
     * }
     */
    public static int RCL_ERROR_MEMORY_ALLOCATION() {
        return (int)1L;
    }
    /**
     * {@snippet :
     * enum .RCL_ERROR_UNKNOWN = 2;
     * }
     */
    public static int RCL_ERROR_UNKNOWN() {
        return (int)2L;
    }
    public static MethodHandle rcl_open$MH() {
        return RuntimeHelper.requireNonNull(constants$0.rcl_open$MH,"rcl_open");
    }
    /**
     * {@snippet :
     * rcl_result rcl_open(char* dir, uint64_t ram_limit, rcl_t** db);
     * }
     */
    public static int rcl_open(MemorySegment dir, long ram_limit, MemorySegment db) {
        var mh$ = rcl_open$MH();
        try {
            return (int)mh$.invokeExact(dir, ram_limit, db);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle rcl_free$MH() {
        return RuntimeHelper.requireNonNull(constants$0.rcl_free$MH,"rcl_free");
    }
    /**
     * {@snippet :
     * void rcl_free(rcl_t* db);
     * }
     */
    public static void rcl_free(MemorySegment db) {
        var mh$ = rcl_free$MH();
        try {
            mh$.invokeExact(db);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle rcl_update_height$MH() {
        return RuntimeHelper.requireNonNull(constants$0.rcl_update_height$MH,"rcl_update_height");
    }
    /**
     * {@snippet :
     * rcl_result rcl_update_height(rcl_t* db, uint64_t height);
     * }
     */
    public static int rcl_update_height(MemorySegment db, long height) {
        var mh$ = rcl_update_height$MH();
        try {
            return (int)mh$.invokeExact(db, height);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle rcl_set_upstream$MH() {
        return RuntimeHelper.requireNonNull(constants$0.rcl_set_upstream$MH,"rcl_set_upstream");
    }
    /**
     * {@snippet :
     * rcl_result rcl_set_upstream(rcl_t* db, char* upstream);
     * }
     */
    public static int rcl_set_upstream(MemorySegment db, MemorySegment upstream) {
        var mh$ = rcl_set_upstream$MH();
        try {
            return (int)mh$.invokeExact(db, upstream);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle rcl_query$MH() {
        return RuntimeHelper.requireNonNull(constants$0.rcl_query$MH,"rcl_query");
    }
    /**
     * {@snippet :
     * rcl_result rcl_query(rcl_t* db, rcl_query_t* query, uint64_t* result);
     * }
     */
    public static int rcl_query(MemorySegment db, MemorySegment query, MemorySegment result) {
        var mh$ = rcl_query$MH();
        try {
            return (int)mh$.invokeExact(db, query, result);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle rcl_insert$MH() {
        return RuntimeHelper.requireNonNull(constants$0.rcl_insert$MH,"rcl_insert");
    }
    /**
     * {@snippet :
     * rcl_result rcl_insert(rcl_t* db, size_t size, rcl_log_t* logs);
     * }
     */
    public static int rcl_insert(MemorySegment db, long size, MemorySegment logs) {
        var mh$ = rcl_insert$MH();
        try {
            return (int)mh$.invokeExact(db, size, logs);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle rcl_logs_count$MH() {
        return RuntimeHelper.requireNonNull(constants$1.rcl_logs_count$MH,"rcl_logs_count");
    }
    /**
     * {@snippet :
     * rcl_result rcl_logs_count(rcl_t* db, uint64_t* result);
     * }
     */
    public static int rcl_logs_count(MemorySegment db, MemorySegment result) {
        var mh$ = rcl_logs_count$MH();
        try {
            return (int)mh$.invokeExact(db, result);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle rcl_blocks_count$MH() {
        return RuntimeHelper.requireNonNull(constants$1.rcl_blocks_count$MH,"rcl_blocks_count");
    }
    /**
     * {@snippet :
     * rcl_result rcl_blocks_count(rcl_t* db, uint64_t* result);
     * }
     */
    public static int rcl_blocks_count(MemorySegment db, MemorySegment result) {
        var mh$ = rcl_blocks_count$MH();
        try {
            return (int)mh$.invokeExact(db, result);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}


