name: Build Java Lib
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-macos-dylib:
    name:  Build dylib for macos
    runs-on: macos-latest
    env: { CC: "clang" }
    steps:
    - uses: actions/checkout@v3
    - run: |
        brew install llvm@15
        brew fetch --force --arch=arm curl cjson
        brew fetch --force --arch=intel curl cjson

    - run: |
        brew reinstall $(brew --cache --arch=arm curl cjson)
        make CFLAGS="-arch arm64" -j $(nproc) clean liboracle.so 
        mv liboracle.so liboracle-arm64-macos.dylib
    - run: |
        brew reinstall $(brew --cache --arch=intel curl cjson)
        make CFLAGS="-arch x86_64" -j $(nproc) clean liboracle.so 
        mv liboracle.so liboracle-x86_64-macos.dylib

    - uses: actions/upload-artifact@v3
      with:
        name: liboracle-macos
        path: liboracle-*-macos.dylib

  build-linux-so:
    name:  Build dylib for linux
    runs-on: ubuntu-latest
    env: { CC: "clang" }
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update
        sudo apt-get install -y clang-12 libcjson-dev libcurl4-openssl-dev

    - run: |
        make CFLAGS="-march=x86-64-v4" -j $(nproc) liboracle.so 
        mv liboracle.so liboracle-x86_64-linux.so

    - uses: actions/upload-artifact@v3
      with:
        name: liboracle-linux
        path: liboracle-x86_64-linux.so

  build-jar:
    name: Build jar
    needs: ['build-macos-dylib', 'build-linux-so']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3 
      with:
        distribution: 'zulu'
        java-version: 20

    - uses: actions/download-artifact@v3
      with: { name: 'liboracle-macos' }
    - uses: actions/download-artifact@v3
      with: { name: 'liboracle-linux' }

    - run: make java/LogsOracle.jar
    - run: |
        jar uf java/LogsOracle.jar liboracle-x86_64-linux.so
        jar uf java/LogsOracle.jar liboracle-x86_64-macos.dylib
        jar uf java/LogsOracle.jar liboracle-arm64-macos.dylib

    - uses: actions/upload-artifact@v3
      with:
        name: LogsOracle.jar
        path: java/LogsOracle.jar
