name: Build and tests

on:
  push:
    branches: [ main, 'v0.[0-9]+' ]
  pull_request:
    branches: [ main, 'v0.[0-9]+' ]

    
permissions:
  contents: read

jobs:
  tests:
    name: "Tests: ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GO toolchain
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: Install build deps
        run: sudo apt-get install libcriterion-dev

      - name: liboracle unit tests
        run: make test
